### ISSUE TITLE
enabled field is missing when create JSEC tunnel

### ISSUE THREAD

**Issue by lzhang-AIDE** [Juniper/terraform-provider-mist#120]
## Describe the bug
JSEC tunnel could not be created when using the following resource in "org_gatewaytemplate"

## Terraform configuration
tunnel_configs = {
    JSEC_WAN0 = {
    auto_provision = {
    provider = "jse-ipsec"
    primary = {
        probe_ips = [
                "8.8.8.8"
        ]
        wan_names = [
                "wan0"
        ]
    }
    secondary = {
        probe_ips = [
                "8.8.8.8"
        ]
        wan_names = [
                "wan0"
        ]
    }
    enabled = true
    }
    }

    }

## Expected behavior
"enabled = true" should be committed.

## Error Message
There is no "enabled" filed in template endpoint. And this causes JSEC tunnel could not be created.
https://api.mistsys.com/api/v1/orgs/?org_id/gatewaytemplates/?template_id
tunnel_configs": {
        "JSEC_WAN0": {
            "auto_provision": {
                "primary": {
                    "probe_ips": [
                        "8.8.8.8"
                    ],
                    "wan_names": [
                        "wan0"
                    ]
                },
                "provider": "jse-ipsec",
                "secondary": {
                    "probe_ips": [
                        "8.8.8.8"
                    ],
                    "wan_names": [
                        "wan0"
                    ]
                }
            },
            "ike_mode": "main",
            "mode": "active-standby",
            "version": "2"
        }
    },

## Additional context
mist v0.4.3

**Comment by tmunzer** [comment]
Hi @lzhang-AIDE,

there was a typo in the OAS (it was "enable" and not "enabled"). I fixed that and it will be part of the next version

**Comment by tmunzer** [comment]
Hi @lzhang-AIDE ,

v0.4.5 has been released and should fix your issue. Can you validate?

Thanks,

**Comment by lzhang-AIDE** [comment]
Hi @tmunzer 
The issue still exists with v0.4.5. Could you help to check?
(base) lzhang@lzhang-mbp test_staging_debug % terraform init 
Initializing the backend...
Initializing provider plugins...
- Reusing previous version of juniper/mist from the dependency lock file
- Using previously-installed juniper/mist v0.4.5


main.tf

<img width="602" height="1486" alt="Image" src="https://github.com/user-attachments/assets/393987a4-8c28-4d13-bbfc-782088de56be" />

Mist endpoint

<img width="616" height="1688" alt="Image" src="https://github.com/user-attachments/assets/2de07000-76bc-4dca-b637-c58233f61d8f" />

Thanks.

**Comment by tmunzer** [comment]
Hi @lzhang-AIDE 

I tried your configuration on my side, and it is generating the correct Mist payload:
```json
"tunnel_configs": {
            "JSEC_WANO": {
                "auto_provision": {
                    "enabled": true,
                    "primary": {
                        "probe_ips": [
                            "8.8.8.8"
                        ],
                        "wan_names": [
                            "wan0"
                        ]
                    },
                    "provider": "jse-ipsec",
                    "secondary": {
                        "probe_ips": [
                            "8.8.8.8"
                        ],
                        "wan_names": [
                            "wan0"
                        ]
                    }
                }
            }
```


Can you double check?

**Comment by lzhang-AIDE** [comment]
I pull the latest code and run go install. Now the "enabled" is set correctly. Thanks.
Mist payload:

<img width="676" height="1562" alt="Image" src="https://github.com/user-attachments/assets/c063ef69-b6e8-4c6f-8ddc-05d07e354750" />

**Comment by tmunzer** [comment]
Thanks for the confirmation. I'll close the issue
